# Generated by Django 3.1.6 on 2021-02-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('image', models.URLField(default='https://www.talk-recruitment.co.uk/userfiles/TalkRecruitment/WebContent/mood%20lighting.jpg?created=20-09-08-12-19-42"')),
            ],
        ),
    ]
