# Generated by Django 3.1.6 on 2021-02-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='image',
            field=models.URLField(default='https://dt7v1i9vyp3mf.cloudfront.net/styles/news_large/s3/imagelibrary/Q/QA_2-0812-iEt6DpElf7a6Bfqjbzsp_.4z1MoTRa0n.jpg'),
        ),
    ]
